module.exports = {
  formatLibrary: [['javascript', 'js-beautify-js'],
    ['json', 'js-beautify-js'],
    ['XML', 'js-beautify-html'],
    ['css', 'js-beautify-css']], // ['Language code', 'Format library']
  languageItemsValue: [['autodetect', 'autodetect', 'Autodetect'],
    ['javascript', 'javascript1', 'JavaScript'],
    ['json', 'json1', 'JSON'],
    ['css', 'css1', 'CSS'],
    ['XML', 'XML1', 'HTML / XML'],
    ['java', 'java1', 'Java'],
    ['python', 'python1', 'Python'],
    ['php', 'php1', 'PHP'],
    ['ruby', 'ruby1', 'Ruby'],
    ['cpp', 'cpp1', 'C / C++'],
    ['shell', 'shell1', 'Shell'],
    ['cs', 'cs1', 'C#'],
    ['go', 'go1', 'Go'],
    ['auto', 'auto', '--------'],
    ['1c', '1c', '1C'],
    ['abnf', 'abnf', 'ABNF'],
    ['accesslog', 'accesslog', 'Access logs'],
    ['ada', 'ada', 'Ada'],
    ['armasm', 'armasm', 'ARM assembler'],
    ['avrasm', 'avrasm', 'AVR assembler'],
    ['actionscript', 'actionscript', 'ActionScript'],
    ['apache', 'apache', 'Apache'],
    ['applescript', 'applescript', 'AppleScript'],
    ['asciidoc', 'asciidoc', 'AsciiDoc'],
    ['aspectj', 'aspectj', 'AspectJ'],
    ['autohotkey', 'autohotkey', 'AutoHotkey'],
    ['autoit', 'autoit', 'AutoIt'],
    ['awk', 'awk', 'Awk'],
    ['axapta', 'axapta', 'Axapta'],
    ['bash', 'bash', 'Bash'],
    ['basic', 'basic', 'Basic'],
    ['bnf', 'bnf', 'BNF'],
    ['brainfuck', 'brainfuck', 'Brainfuck'],
    ['cs', 'cs', 'C#'],
    ['cpp', 'cpp', 'C / C++'],
    ['cal', 'cal', 'C / AL'],
    ['cos', 'cos', 'Cache Object Script'],
    ['cmake', 'cmake', 'CMake'],
    ['coq', 'coq', 'Coq'],
    ['csp', 'csp', 'CSP'],
    ['css', 'css', 'CSS'],
    ['capnproto', 'capnproto', 'Cap’n Proto'],
    ['clojure', 'clojure', 'Clojure'],
    ['coffeescript', 'coffeescript', 'CoffeeScript'],
    ['crmsh', 'crmsh', 'Crmsh'],
    ['crystal', 'crystal', 'Crystal'],
    ['d', 'd', 'D'],
    ['dns', 'dns', 'DNS Zone file'],
    ['dos', 'dos', 'DOS'],
    ['dart', 'dart', 'Dart'],
    ['delphi', 'delphi', 'Delphi'],
    ['diff', 'diff', 'Diff'],
    ['django', 'django', 'Django'],
    ['dockerfile', 'dockerfile', 'Dockerfile'],
    ['dsconfig', 'dsconfig', 'dsconfig'],
    ['dts', 'dts', 'DTS (Device Tree)'],
    ['dust', 'dust', 'Dust'],
    ['ebnf', 'ebnf', 'EBNF'],
    ['elixir', 'elixir', 'Elixir'],
    ['elm', 'elm', 'Elm'],
    ['erlang', 'erlang', 'Erlang'],
    ['excel', 'excel', 'Excel'],
    ['fsharp', 'fsharp', 'F#'],
    ['fix', 'fix', 'FIX'],
    ['fortran', 'fortran', 'Fortran'],
    ['gcode', 'gcode', 'G-Code'],
    ['gams', 'gams', 'Gams'],
    ['gauss', 'gauss', 'GAUSS'],
    ['gherkin', 'gherkin', 'Gherkin'],
    ['go', 'go', 'Go'],
    ['golo', 'golo', 'Golo'],
    ['gradle', 'gradle', 'Gradle'],
    ['groovy', 'groovy', 'Groovy'],
    ['XML', 'HTML', 'HTML / XML'],
    ['http', 'http', 'HTTP'],
    ['haml', 'haml', 'Haml'],
    ['handlebars', 'handlebars', 'Handlebars'],
    ['haskell', 'haskell', 'Haskell'],
    ['haxe', 'haxe', 'Haxe'],
    ['ini', 'ini', 'Ini'],
    ['inform7', 'inform7', 'Inform7'],
    ['irpf90', 'irpf90', 'IRPF90'],
    ['json', 'json', 'JSON'],
    ['java', 'java', 'Java'],
    ['javascript', 'javascript', 'JavaScript'],
    ['lasso', 'lasso', 'Lasso'],
    ['less', 'less', 'Less'],
    ['ldif', 'ldif', 'LDIF'],
    ['lisp', 'lisp', 'Lisp'],
    ['livecodeserver', 'livecodeserver', 'LiveCode Server'],
    ['livescript', 'livescript', 'LiveScript'],
    ['lua', 'lua', 'Lua'],
    ['makefile', 'makefile', 'Makefile'],
    ['markdown', 'markdown', 'Markdown'],
    ['mathematica', 'mathematica', 'Mathematica'],
    ['matlab', 'matlab', 'Matlab'],
    ['maxima', 'maxima', 'Maxima'],
    ['mel', 'mel', 'Maya Embedded Language'],
    ['mercury', 'mercury', 'Mercury'],
    ['mizar', 'mizar', 'Mizar'],
    ['mojolicious', 'mojolicious', 'Mojolicious'],
    ['monkey', 'monkey', 'Monkey'],
    ['moonscript', 'moonscript', 'Moonscript'],
    ['nsis', 'nsis', 'NSIS'],
    ['nginx', 'nginx', 'Nginx'],
    ['nimrod', 'nimrod', 'Nimrod'],
    ['nix', 'nix', 'Nix'],
    ['ocaml', 'ocaml', 'OCaml'],
    ['objectivec', 'objectivec', 'Objective C'],
    ['glsl', 'glsl', 'OpenGL Shading Language'],
    ['openscad', 'openscad', 'OpenSCAD'],
    ['ruleslanguage', 'ruleslanguage', 'Oracle Rules Language'],
    ['oxygene', 'oxygene', 'Oxygene'],
    ['pf', 'pf', 'PF'],
    ['php', 'php', 'PHP'],
    ['parser3', 'parser3', 'Parser3'],
    ['perl', 'perl', 'Perl'],
    ['pony', 'pony', 'Pony'],
    ['powershell', 'powershell', 'PowerShell'],
    ['processing', 'processing', 'Processing'],
    ['prolog', 'prolog', 'Prolog'],
    ['protobuf', 'protobuf', 'Protocol Buffers'],
    ['puppet', 'puppet', 'Puppet'],
    ['python', 'python', 'Python'],
    ['profile', 'profile', 'Python profiler results'],
    ['k', 'k', 'Q'],
    ['qml', 'qml', 'QML'],
    ['r', 'r', 'R'],
    ['rib', 'rib', 'RenderMan RIB'],
    ['rsl', 'rsl', 'RenderMan RSL'],
    ['graph', 'graph', 'Roboconf'],
    ['ruby', 'ruby', 'Ruby'],
    ['rust', 'rust', 'Rust'],
    ['scss', 'scss', 'SCSS'],
    ['sql', 'sql', 'SQL'],
    ['p21', 'p21', 'STEP Part 21'],
    ['scala', 'scala', 'Scala'],
    ['scheme', 'scheme', 'Scheme'],
    ['scilab', 'scilab', 'Scilab'],
    ['smali', 'smali', 'Smali'],
    ['smalltalk', 'smalltalk', 'Smalltalk'],
    ['stan', 'stan', 'Stan'],
    ['stata', 'stata', 'Stata'],
    ['stylus', 'stylus', 'Stylus'],
    ['subunit', 'subunit', 'SubUnit'],
    ['swift', 'swift', 'Swift'],
    ['tap', 'tap', 'Test Anything Protocol'],
    ['tcl', 'tcl', 'Tcl'],
    ['tex', 'tex', 'TeX'],
    ['thrift', 'thrift', 'Thrift'],
    ['tp', 'tp', 'TP'],
    ['twig', 'twig', 'Twig'],
    ['typescript', 'typescript', 'TypeScript'],
    ['vbnet', 'vbnet', 'VB.Net'],
    ['vbscript', 'vbscript', 'VBScript'],
    ['vhdl', 'vhdl', 'VHDL'],
    ['vala', 'vala', 'Vala'],
    ['verilog', 'verilog', 'Verilog'],
    ['vim', 'vim', 'Vim Script'],
    ['x86asm', 'x86asm', 'x86 Assembly'],
    ['xl', 'xl', 'XL'],
    ['xpath', 'xpath', 'XQuery'],
    ['zephir', 'zephir', 'Zephir']], // ['value/language code','key','primaryText / language name']
  templateItemsValue: [
    ['Agate', 'agate'],
    ['Androidstudio', 'androidstudio'],
    ['ArduinoLight', 'arduino-light'],
    ['Arta', 'arta'],
    ['Ascetic', 'ascetic'],
    ['AtelierCaveDark', 'atelier-cave-dark'],
    ['AtelierCaveLight', 'atelier-cave-light'],
    ['AtelierDuneDark', 'atelier-dune-dark'],
    ['AtelierDuneLight', 'atelier-dune-light'],
    ['AtelierEstuaryDark', 'atelier-estuary-dark'],
    ['AtelierEstuaryLight', 'atelier-estuary-light'],
    ['AtelierForestDark', 'atelier-forest-dark'],
    ['AtelierForestLight', 'atelier-forest-light'],
    ['AtelierHeathDark', 'atelier-heath-dark'],
    ['AtelierHeathLight', 'atelier-heath-light'],
    ['AtelierLakesideDark', 'atelier-lakeside-dark'],
    ['AtelierLakesideLight', 'atelier-lakeside-light'],
    ['AtelierPlateauDark', 'atelier-plateau-dark'],
    ['AtelierPlateauLight', 'atelier-plateau-light'],
    ['AtelierSavannaDark', 'atelier-savanna-dark'],
    ['AtelierSavannaLight', 'atelier-savanna-light'],
    ['AtelierSeasideDark', 'atelier-seaside-dark'],
    ['AtelierSeasideLight', 'atelier-seaside-light'],
    ['AtelierSulphurpoolDark', 'atelier-sulphurpool-dark'],
    ['AtelierSulphurpoolLight', 'atelier-sulphurpool-light'],
    ['AtomOneDark', 'atom-one-dark'],
    ['AtomOneLight', 'atom-one-light'],
    ['BrownPaper', 'brown-paper'],
    ['CodepenEmbed', 'codepen-embed'],
    ['ColorBrewer', 'color-brewer'],
    ['Dark', 'dark'],
    ['Darkula', 'darkula'],
    ['Docco', 'docco'],
    ['Dracula', 'dracula'],
    ['Far', 'far'],
    ['Foundation', 'foundation'],
    ['GithubGist', 'github-gist'],
    ['Github', 'github'],
    ['Googlecode', 'googlecode'],
    ['Grayscale', 'grayscale'],
    ['GruvboxDark', 'gruvbox-dark'],
    ['GruvboxLight', 'gruvbox-light'],
    ['Hopscotch', 'hopscotch'],
    ['Hybrid', 'hybrid'],
    ['Idea', 'idea'],
    ['IrBlack', 'ir-black'],
    ['KimbieDark', 'kimbie.dark'],
    ['KimbieLight', 'kimbie.light'],
    ['Magula', 'magula'],
    ['MonoBlue', 'mono-blue'],
    ['MonokaiSublime', 'monokai-sublime'],
    ['Monokai', 'monokai'],
    ['Obsidian', 'obsidian'],
    ['Ocean', 'ocean'],
    ['ParaisoDark', 'paraiso-dark'],
    ['ParaisoLight', 'paraiso-light'],
    ['Pojoaque', 'pojoaque'],
    ['Purebasic', 'purebasic'],
    ['QtcreatorDark', 'qtcreator_dark'],
    ['QtcreatorLight', 'qtcreator_light'],
    ['Railscasts', 'railscasts'],
    ['Rainbow', 'rainbow'],
    ['SchoolBook', 'school-book'],
    ['SolarizedDark', 'solarized-dark'],
    ['SolarizedLight', 'solarized-light'],
    ['Sunburst', 'sunburst'],
    ['TomorrowNightBlue', 'tomorrow-night-blue'],
    ['TomorrowNightBright', 'tomorrow-night-bright'],
    ['TomorrowNightEighties', 'tomorrow-night-eighties'],
    ['TomorrowNight', 'tomorrow-night'],
    ['Tomorrow', 'tomorrow'],
    ['Vs', 'vs'],
    ['Xcode', 'xcode'],
    ['Xt256', 'xt256'],
    ['Zenburn', 'zenburn']
  ]// [Template name, Template style file]
}
